version: '3.7'
volumes:
  data:
networks:
  frontend:
  backend:
services:
  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    restart: always
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
  django:
    image: 
  db:
    image: postgres
    volumes:
      data:/data/db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
